Added code for global evaluation of WIT
Glovo/foodi-ml-dataset pull request #23
Opened 2021-11-17 11:35 UTC by pppuigdevall

* Added code for global evaluation with WIT

2021-11-22 09:27 UTC, asalvadorpalau requested changes

2021-11-22 09:27 UTC, asalvadorpalau commented on benchmarks/wit/evaluate_network_bigdata.py
> +    PATH_I2T_METRICS = "./i2t_metrics.pkl"
Are this paths not too sagemaker specific? should we use ./ and ../?

2021-11-22 09:30 UTC, pppuigdevall commented on benchmarks/wit/evaluate_network_bigdata.py
> +    PATH_I2T_METRICS = "./i2t_metrics.pkl"
Yes, you're right. I think we should add them as arguments instead of hardcoding them, I will set `DATASET_PATH` and `CODE_PATH` as arguments.

2021-11-23 16:01 UTC, DavidAmatGlovo commented
LGTM!

2021-11-23 16:05 UTC, DavidAmatGlovo approved these changes
LGTM!

2021-11-23 16:05 UTC, pppuigdevall commented on benchmarks/wit/evaluate_network_bigdata.py
> +    ----------
Thanks for spotting that David, changing it right away

2021-11-23 16:22 UTC, merged